kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-build"
  annotations:
    tags: sit,sample
message: 'The following service(s) have been created in your project: ${NAME}'
labels:
  template: sample
  app: sample
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    source:
      type: Binary
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: jboss-fuse70-eap-openshift:1.0
        buildArgs:
        - name: appname
          value: "${NAME}"
        env: []
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: sample
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  required: true
  value: sit
- name: JDK_VERSION
  displayName: Version of JDK Image
  description: Version of JDK image to be used (8, 12, or latest).
  value: '8'