kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-deploy"
  annotations:
    tags: sit,dde
message: 'The following service(s) have been created in your project: ${NAME}'
labels:
  template: dde
  app: dde
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: rest
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: "${NAME}"
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: 'true'
    namespace: "${NAMESPACE}"
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentconfig: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          type: apps
          deploymentconfig: "${NAME}"
      spec:
        containers:
        - name: "${NAME}"
          image: "${NAME}"
          ports:
          - name: rest
            containerPort: 8080
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
              cpu: "${CPU_LIMIT}"
            requests:
              memory: "${MEMORY_REQUEST}"
              cpu: "${CPU_REQUEST}"
          env:
          - name: JAVA_ARGS
            value: "-Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom -Xshareclasses -Xquickstart"
          - name: TZ
            value: Asia/Bangkok
          - name: UAT2_DefaultUserId
            value: dsladm
          - name: UAT2_DefaultPassword
            value: dsladm#
          - name: UAT2_DefaultDB
            value: jdbc:oracle:thin:@10.9.225.194:1522:ESLUAT
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: dde
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  required: true
  value: sit
- name: HEALTHCHECK_PATH
  displayName: Healthcheck Path
  description: API Get Path for Liveness and Readyness probe.
  required: true
  value: "/healthz"
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  required: true
  value: 2Gi
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  required: true
  value: 1Gi
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of cpu the container can use.
  required: true
  value: '2'
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of cpu the container can use.
  required: true
  value: '0.5'